repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        files: ^(cookiecutter_uv/|tests/|docs/).*\.json$
      - id: pretty-format-json
        files: ^(cookiecutter_uv/|tests/|docs/).*\.json$
        args: [--autofix, --no-sort-keys]
      - id: check-toml
        files: ^(cookiecutter_uv/|tests/|docs/).*\.toml$
      - id: check-yaml
        files: ^(cookiecutter_uv/|tests/|docs/).*\.ya?ml$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.7"
    hooks:
      - id: ruff-check
        args: [--exit-non-zero-on-fix, --config=pyproject.toml]
        files: ^(cookiecutter_uv/|tests/).*\.py$
      - id: ruff-format
        args: [--config=pyproject.toml]
        files: ^(cookiecutter_uv/|tests/).*\.py$
